### ISSUE TITLE
SSL Error when running get tags

### ISSUE THREAD

**Issue by longx3hg** [phillychi3/nhentai-favorites#2]
https://github.com/phillychi3/nhentai-favorites/blob/2f3f03bcb1474cc37ef345d19415889b0e1ca448/gettags.py#L20
I am currently experiencing an SSL Error when running the get tag method. The error message I am receiving is as follows:
```
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 312, in __init__
    raise x
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: /tags/?page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\GitHub\nhentai-favorites\nfavorites.py", line 63, in <module>
    get_tags()
  File "d:\GitHub\nhentai-favorites\gettags.py", line 20, in get_tags
    data = requests.get(f"{url}?page={now}", headers=headers)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: /tags/?page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```
Environment:
- OS: Windows 11 Home Insider
- Python 3.10.2
- Dependencies: 
   - PyYAML: 6.0
   - fake-useragent: 1.1.1
   - gevent: 22.10.2
   - progress: 1.6
   - requests: 2.28.2
   - bs4: 0.0.1
   - urllib3: 1.26.15

Could someone provide some guidance on how to resolve it? Thank you!

**Comment by phillychi3** [comment]
should be fix

**Comment by longx3hg** [comment]
The same error when running on local. I tried it on codespaces but got 403 error. I am using proton vpn because the ISP is blocking nhentai in my country

**Comment by phillychi3** [comment]
Sorry I can't reproduce it.

**Comment by longx3hg** [comment]
> Sorry I can't reproduce it.

Nhentai is dns blocked in my country. I found the alternative way by using js to scrape from html (the downside is that it can't capture the tags)
